<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Identity Login Test Cases"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="146.890">
  <properties />
            <testcase name="verify_GigyaIdFlow" time="88.015" classname="com.CA.testcases.FulfilmentCRMTest">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	Gigya Id not updated with the flow expected [false] but found [true]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	Gigya Id not updated with the flow expected [false] but found [true]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  com.CA.pages.FulfilmentCRM.verifyGigyaIdFlow(FulfilmentCRM.java:363)
  com.CA.testcases.FulfilmentCRMTest.verify_GigyaIdFlow(FulfilmentCRMTest.java:45)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="verify_loginFulfilment" time="24.680" classname="com.CA.testcases.FulfilmentCRMTest" />
                <testcase name="verify_MandatoryFields" time="23.297" classname="com.CA.testcases.FulfilmentCRMTest" />
                <testcase name="verify_NewFulfilment" time="6.322" classname="com.CA.testcases.FulfilmentCRMTest" />
                <testcase name="verify_SaveAndCheckMandateFields" time="4.576" classname="com.CA.testcases.FulfilmentCRMTest" />
      
</testsuite>
